trigger: none

schedules:
- cron: "30 18 * * *"
# - cron: "*/10 * * * *"
# - cron: "* * * * *"
  displayName: Test Scheduled Failure
  branches:
    include:
    - main
  always: true

pool: datadog

steps:
- script: |
    echo "Simulating scheduled failure"
    exit 1
  displayName: Force Failure